# GitHub Labels for Kinetic
# Apply with: gh label create -R noncelogic/kinetic "name" -c "color" -d "description"

labels:
  # Type
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: question
    color: d876e3
    description: Further information is requested

  # Status
  - name: triage
    color: fbca04
    description: Needs triage
  - name: confirmed
    color: 0e8a16
    description: Bug confirmed, ready to fix
  - name: wontfix
    color: ffffff
    description: This will not be worked on
  - name: duplicate
    color: cfd3d7
    description: This issue or PR already exists

  # Priority
  - name: "priority: critical"
    color: b60205
    description: Must be fixed ASAP
  - name: "priority: high"
    color: d93f0b
    description: Should be fixed soon
  - name: "priority: medium"
    color: fbca04
    description: Normal priority
  - name: "priority: low"
    color: c2e0c6
    description: Nice to have

  # Area
  - name: "area: auth"
    color: 5319e7
    description: Authentication related
  - name: "area: database"
    color: 5319e7
    description: Database/Prisma related
  - name: "area: ui"
    color: 5319e7
    description: UI components
  - name: "area: api"
    color: 5319e7
    description: tRPC/API related
  - name: "area: dx"
    color: 5319e7
    description: Developer experience

  # Meta
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: breaking change
    color: b60205
    description: Introduces breaking changes
